# Use the already built image as the base
FROM ghcr.io/ghazi-nk/troubledetector:latest

# Copy the Sonar report output file into the image
COPY sonar_output.json /app/sonar_output.json

# Expose the port
EXPOSE 7861

CMD ["python", "mcp_server/mcp_server.py"]