apiVersion: apps/v1
kind: Deployment
metadata:
  name: troubledetector-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troubledetector-app
  template:
    metadata:
      labels:
        app: troubledetector-app
    spec:
      containers:
        - name: troubledetector
          image: ghcr.io/ghazi-nk/troubledetector-with-semgrep:latest
          ports:
            - containerPort: 7861
          # command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
      imagePullSecrets:
        - name: ghcr-secret  # Das ImagePullSecret, das du vorher erstellt hast
