apiVersion: v1
kind: Service
metadata:
  name: troubledetector-service
spec:
  selector:
    app: troubledetector
  ports:
    - protocol: TCP
      port: 7861
      targetPort: 7861
  type: ClusterIP