name: CI - Docker Build and Semgrep Scan

on:
  push:
    branches:
      - main
      - master
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: '12 15 * * *'  # random time to avoid GitHub load spikes

env:
  USER: "ghazi-nk"

jobs:
  docker-build:
    name: Docker Image Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$USER/troubledetector:latest .

  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep ci
