name: Docker Build and Semgrep Scan

on: [push]

env:
  USER: "ghazi-nk"

jobs:
  docker-semgrep:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Login to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 3: Build the base Docker image
      - name: Build base Docker image
        run: |
          docker build -t ghcr.io/$USER/troubledetector:latest .

      # Step 4: Run Semgrep scan and output report.json
      - name: Run Semgrep scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            -v "${{ github.workspace }}/semgrep_output:/output" \
            -e SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_APP_TOKEN }} \
            semgrep/semgrep semgrep ci --json --output /output/report.json

      # Step 5: Copy Semgrep report to the workspace
      - name: Prepare Semgrep report
        run: cp semgrep_output/report.json .

      # Step 6: Build the final Docker image including report.json
      - name: Build final image with Semgrep report
        run: |
          docker build -t ghcr.io/$USER/troubledetector-with-semgrep:latest -f Dockerfile.semgrep .

      # Step 7: Push the final image to GHCR
      - name: Push final image
        run: docker push ghcr.io/$USER/troubledetector-with-semgrep:latest
